apiVersion: v1
kind: recipe
metadata:
  id: zillow/google-sheets
  version: 0.0.1
  name: Send Zillow Properties to Google Sheets
  description: Send Zillow properties you've found to Google Sheets
extensionPoints:
  - id: zillow/property-button
    label: Send Property to Google Sheets
    services:
      sheet: "google/sheet"
    config:
      caption: Sheets
      icon:
        id: googlesheets
        library: simple-icons
        size: 24
      action:
        - id: "@pixiebrix/google/sheets-append"
          config:
            spreadsheetId: "@sheet.spreadsheetId"
            tabName: "Zillow"
            rowValues:
              - header: Zillow Id
                value: zpid
              - header: MLS ID
                value: mlsid
              - header: Address
                value: address.streetAddress
              - header: City
                value: address.city
              - header: State
                value: address.state
              - header: Price
                value: price
              - header: "# Beds"
                value: bedrooms
              - header: "# Full Baths"
                value: bathrooms
              - header: Built
                value: yearBuilt
              - header: Latitude
                value: latitude
              - header: Longitude
                value: longitude
              - header: Retrieved From
                value: document.url
