apiVersion: v1
kind: extensionPoint
metadata:
  id: zillow/property-button
  version: 0.0.1
  name: Zillow Button
  description: Add a Button to Zillow's Property Action Menu
definition:
  type: menuItem
  reader:
    - zillow/property
    - document: "@pixiebrix/document-context"
  isAvailable:
    matchPatterns: https://www.zillow.com/homedetails/*
  containerSelector:
    - ".details-page-container"
    - ".ds-action-bar"
    - "ul"
  template: |
    <li>
      <button aria-pressed="false">
        <div>
          <div aria-hidden="true">
            {{&icon}}
          </div>
          <span> {{caption}}<!-- --> </span>
        </div>
      </button>
    </li>
