# Documentation
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Updates can also be manually requested by clicking "Last checked 3 days ago" on the page
# https://github.com/pixiebrix/pixiebrix-extension/network/updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      time: "08:42"
      timezone: "Etc/UTC"
    versioning-strategy: increase # Update package.json too https://stackoverflow.com/a/66819358/288906
    open-pull-requests-limit: 20
    reviewers:
      - "fregante"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "08:42"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 20
    reviewers:
      - "fregante"
