# Documentation
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Updates can also be manually requested by clicking "Last checked 3 days ago" on the page
# https://github.com/pixiebrix/pixiebrix-extension/network/updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /applications/browser-extension/
    schedule:
      interval: weekly
      day: sunday
      time: "08:42"
      timezone: Etc/UTC
    versioning-strategy: increase # Update package.json too https://stackoverflow.com/a/66819358/288906
    open-pull-requests-limit: 30
    assignees:
      - grahamlangford
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - patch
      rjsf:
        patterns:
          - "@rjsf/*"
      # Until https://github.com/pixiebrix/pixiebrix-extension/issues/7915
      # storybook:
      #   patterns:
      #     - "*storybook*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      datadog:
        patterns:
          - "@datadog/*"
    ignore:
      # Until https://github.com/pixiebrix/pixiebrix-extension/issues/7915
      - dependency-name: "*storybook*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "08:42"
      timezone: Etc/UTC
    open-pull-requests-limit: 30
    assignees:
      - grahamlangford
