# https://pre-commit.com/hooks.html

# The hooks can be updated with:
# pre-commit autoupdate
#
# And then run updated hooks against all files with:
# pre-commit run --all-files
exclude: __snapshots__/|package-lock.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: detect-private-key
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
#  - repo: local
#    hooks:
#      - id: eslint
#        name: eslint
#        entry: npm run lint --
#        language: node
#        files: \.js$|\.jsx$|\.ts$|\.tsx$
