# https://pre-commit.com/hooks.html

# The hooks can be updated with:
# pre-commit autoupdate
#
# And then run updated hooks against all files with:
# pre-commit run --all-files
exclude: __snapshots__/|package-lock.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: detect-private-key
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          # mirrors-prettier won't receive updates after v3.1.0 because prettier changed their
          # plugin system: "prettier made some changes that breaks plugins entirely"
          # See: https://github.com/pre-commit/pre-commit/issues/3133
          # The additional_dependencies aren't updated with `pre-commit autoupdate`
          - prettier@3.3.3
  # TODO: restore in https://github.com/pixiebrix/pixiebrix-extension/issues/9441
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       entry: npm run lint:staged --
  #       language: node
  #       files: \.js$|\.jsx$|\.ts$|\.tsx$
