apiVersion: v1
kind: component
metadata:
  id: "reddit/search"
  version: 1.0.0
  name: Reddit Search in new tab
  description: Runs a Reddit search in a new tab
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    query:
      type: string
      description: The search query
    sort:
      type: string
      description: Sort by
      default: relevance
      enum:
        - relevance
        - top
        - hot
        - new
        - comments
    time:
      type: string
      description: Post from
      default: all
      enum:
        - all
        - hour
        - day
        - week
        - month
        - year
  required:
    - query
pipeline:
  - id: "@pixiebrix/browser/open-tab"
    config:
      url: https://www.reddit.com/search/
      params:
        q: query
        t: "{{{ time }}}"
        sort: "{{{ sort }}}"
