apiVersion: v1
kind: extensionPoint
metadata:
  id: "apartments.com/property-button"
  version: 0.0.1
  name: Apartments.com Button
  description: Add a Button to Apartments.com
definition:
  type: menuItem
  reader:
    - "apartments.com/property-reader"
    - document: "@pixiebrix/document-context"
  isAvailable:
    matchPatterns: https://www.apartments.com/*
    selectors: "#propertyHeader"
  containerSelector:
    - "#propertyHeader"
    - ".propertyInformationColumn"
  template: |
    <div class="favoriteBox">
      <a href="#" onClick="javascript:void(0);" title="{{caption}}">{{&icon}}</a>
    </div>
