apiVersion: v1
kind: extensionPoint
metadata:
  id: "linkedin/person-menu"
  version: 0.0.1
  name: LinkedIn Profile Menu Item
  description: Add a menu item to the More... dropdown
definition:
  type: menuItem
  reader: linkedin/person-summary
  isAvailable:
    matchPatterns: https://*.linkedin.com/*
    selectors: "#profile-content"
  defaultOptions:
    caption: "Action for {{firstName}}"
    icon:
      id: box
      library: bootstrap
      size: 11
  containerSelector:
    - ".pv-s-profile-actions__overflow"
    - "ul"
  # TODO: expose the a11y_text and &icon as an input to the extension point
  template: |
    <li class="ember-view">
        <div class="ember-view">
            <div class="pv-s-profile-actions pv-s-profile-actions--share-profile pv-s-profile-actions__overflow-button full-width text-align-left artdeco-dropdown__item artdeco-dropdown__item--is-dropdown ember-view" tabindex="0">
              <li-icon aria-hidden="true" class="pv-s-profile-actions__overflow-icon" size="large">
                {{&icon}}
              </li-icon>
            <span class="display-flex t-normal pv-s-profile-actions__label" aria-hidden="true">{{caption}}</span>
            <span class="a11y-text">{{a11y_text}}</span>
        </div>
        </div>
    </li>
