apiVersion: v1
kind: extensionPoint
metadata:
  id: linkedin/organization-panel
  version: 0.0.1
  name: LinkedIn Company Panel
  description: Add a panel to the LinkedIn company profile page
definition:
  type: panel
  reader: "linkedin/organization-summary"
  isAvailable:
    matchPatterns: https://*.linkedin.com/*
    selectors: ".organization-outlet"
  defaultOptions:
    caption: "Custom Panel for {{companyName}}"
  containerSelector: ".org-grid__core-rail"
  position: prepend
  template: |
    <div class="mb3">
      <section class="pixiebrix artdeco-card mb3">
        <header>
          <h3 class="t-18 pv3 ph4" data-toggle="collapse" data-target="#{{bodyUUID}}">{{heading}}</h3>
        </header>
        <div class="ph4 pb4">
          {{&body}}
        </div>
      </section>
    </div>
