apiVersion: v1
kind: service
metadata:
  id: "automation-anywhere/oauth2"
  version: 3.0.0
  name: Automation Anywhere OAuth2 (Preview)
  description: Preview/test integration of OAuth2 authentication for Automation Anywhere
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    controlRoomUrl:
      type: string
      description: "The Control Room URL, including https://"
      format: uri
  required:
    - controlRoomUrl
authentication:
  baseURL: "{{{ controlRoomUrl }}}"
  oauth2:
    authorizeUrl: "https://oauthconfigapp.automationanywhere.digital/client/oauth/authorize?hosturl={{{ controlRoomUrl }}}&audience=https://controlroom"
    tokenUrl: "https://oauthconfigapp.automationanywhere.digital/client/oauth/token"
    code_challenge_method: S256
    scope: "openid userprofile offline_access"
    client_id: "g2qrB2fvyLYbotkb3zi9wwO5qjmje3eM"
  headers:
    Authorization: "Bearer {{{ access_token }}}"
