apiVersion: v1
kind: service
metadata:
  id: hubspot/api
  version: 1.0.0
  name: Hubspot API
  description: The legacy Hubspot API
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    apiKey:
      $ref: "https://app.pixiebrix.com/schemas/key#"
      description: Your Hubspot API key
  required:
    - apiKey
authentication:
  params:
    hapikey: "{{apiKey}}"
