apiVersion: v1
kind: recipe
metadata:
  id: amazon/template-search
  version: 1.0.0
  name: Amazon Search Context Menu
  description: Amazon search context menus
extensionPoints:
  - id: "@pixiebrix/context-search"
    label: Search Amazon
    config:
      title: Amazon
      action:
        id: amazon/search
        config:
          query: selectionText
  - id: "@pixiebrix/context-search"
    label: Search Books on Amazon
    config:
      title: "Amazon: Books"
      action:
        id: amazon/search
        config:
          query: selectionText
          department: stripbooks
  - id: "@pixiebrix/context-search"
    label: Search Amazon Video
    config:
      title: "Amazon: Video"
      action:
        id: amazon/search
        config:
          query: selectionText
          department: instant-video
