apiVersion: v1
kind: recipe
metadata:
  id: google/template-search
  version: 1.0.0
  name: Google Search Context Menu
  description: Google search context menus
extensionPoints:
  - id: "@pixiebrix/context-search"
    label: Search Google
    config:
      title: Google
      action:
        id: google/search
        config:
          query: selectionText
  - id: "@pixiebrix/context-search"
    label: Search PDFs on Google
    config:
      title: "Google: PDFs"
      action:
        id: google/search
        config:
          query: "filetype:pdf {{{ selectionText }}}"
