apiVersion: v1
kind: service
metadata:
  id: automation-anywhere/control-room
  version: 1.1.0
  name: Automation Anywhere Control Room
  description: Automation Anywhere Control Room API
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    controlRoomUrl:
      type: string
      format: uri
      description: The Automation Anywhere Control Room API base URL, starting with https:// and ending with a domain or IP address (excluding trailing slashes)
      pattern: '^https:\/\/(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])(:\d{1,5})?$'
    apiVersion:
      type: string
      description: Control Room authentication API version. Use v2 for Control Room v.31 and later
      default: v2
      enum:
        - v1
        - v2
    username:
      type: string
      description: The username of the Automation Anywhere user.
    password:
      $ref: "https://app.pixiebrix.com/schemas/key#"
      description: The password of the Automation Anywhere user.
    apiKey:
      $ref: "https://app.pixiebrix.com/schemas/key#"
      description: |
        The apiKey is required to configure Single Sign On (SSO). It can also be used in place of a
        password for users that are assigned to the API key generation role.
    folderId:
      type: string
      description: The folder ID containing the bots to run
      pattern: '\d+'
  required:
    - controlRoomUrl
    - username
uiSchema:
  ui:order:
    - controlRoomUrl
    - apiVersion
    - username
    - password
    - apiKey
    - folderId
    - "*"
authentication:
  baseURL: "{{{ controlRoomUrl }}}"
  token:
    url: "{{{ controlRoomUrl }}}/{{#apiVersion}}{{{.}}}{{/apiVersion}}{{^apiVersion}}v1{{/apiVersion}}/authentication"
    data:
      username: "{{{ username }}}"
      password: "{{{ password }}}"
      apiKey: "{{{ apiKey }}}"
  headers:
    X-Authorization: "{{{ token }}}"
