apiVersion: v1
kind: extensionPoint
metadata:
  id: pipedrive/person-panel
  version: 0.0.1
  name: Pipedrive Person Panel
  description: A Pipedrive person panel
definition:
  type: panel
  reader: pipedrive/person
  isAvailable:
    matchPatterns: https://*.pipedrive.com/person/*
  containerSelector: ".sidebar"
  template: |
    <div class="widget">
        <div class="columnTitle"><span class="columnItem">{{heading}}</span></div>
        <div>{{&body}}</div>
    </div>
