apiVersion: v1
kind: recipe
metadata:
  id: test/definition-example
  version: 1.0.0
  name: Internal Context Menu Extension Pooin
  description: Yelp search context menus
definitions:
  search:
    kind: extensionPoint
    definition:
      type: contextMenu
      reader: "@pixiebrix/document-context"
      contexts:
        - selection
      documentUrlPatterns:
        - "*://*/*"

extensionPoints:
  - id: search
    label: Search Yelp
    config:
      title: Yelp
      action:
        id: yelp/search
        config:
          query: selectionText
