apiVersion: v1
kind: recipe
metadata:
  id: linkedin/hubspot
  version: 0.0.1
  name: LinkedIn HubSpot Integration
  description: LinkedIn HubSpot Integration, e.g., send profiles to HubSpot
extensionPoints:
  - id: "linkedin/contact-info-button"
    label: Create/Update in HubSpot
    services:
      hubspot: hubspot
      geocode: google/geocode
    config:
      caption: Create in HubSpot
      icon:
        id: hubspot
        library: simple-icons
        size: 10
      action:
        - id: pixiebrix/contrib-google/geocode
          outputKey: location
          config:
            service: "@geocode"
            address: locationName
        - id: "@pixiebrix/profile"
          outputKey: profile
        - id: "@pixiebrix/get"
          outputKey: owners
          config:
            service: "@hubspot"
            url: https://api.hubapi.com/owners/v2/owners
            params:
              email: "@profile.email"
        - id: pixiebrix/contrib-hubspot-contact
          config:
            service: "@hubspot"
            email: emailAddress
            firstname: firstName
            lastname: lastName
            company: currentCompanyName
            city: "@location.city"
            state: "@location.state"
            country: "@location.country"
            phone: phoneNumbers?.0.number
            website: websites?.0.url
            address: address
            jobtitle: headline
            hubspot_owner_id: "@owners.0?.ownerId"
  - id: "linkedin/person-panel"
    label: HubSpot Timeline
    services:
      hubspot: hubspot
    config:
      heading: HubSpot Timeline
      collapsible: true
      body:
        id: pixiebrix/contrib-hubspot-contact-timeline
        config:
          hubspotService: "@hubspot"
          query: "{{&firstName}} {{&lastName}} {{&currentCompanyName}}"
  - id: "linkedin/contact-info-entry"
    label: Hubspot Contact Info Entry
    services:
      hubspot: hubspot
    config:
      heading: HubSpot Contact Entry
      shadowDOM: false
      body:
        - id: pixiebrix/hubspot-person-search
          config:
            hubspotService: "@hubspot"
            query: "{{&email}} {{&firstName}} {{&lastName}} {{&currentCompanyName}}"
        - id: pixiebrix/contrib-html
          templateEngine: nunjucks
          config:
            html: |
              {% if vid %}
                <a href="{{profile_url}}" class="pv-contact-info__contact-link link-without-visited-state t-14" target="_blank" rel="noopener noreferrer">View in Hubspot</a>
              {% else %}
                Not found in Hubspot
              {% endif %}
  - id: "linkedin/organization-button"
    label: Hubspot Company Entry
    services:
      hubspot: hubspot
    config:
      caption: Create in HubSpot
      icon:
        id: hubspot
        library: simple-icons
        size: 10
      action:
        - id: "@pixiebrix/profile"
          outputKey: profile
        - id: "@pixiebrix/get"
          outputKey: owners
          config:
            service: "@hubspot"
            url: https://api.hubapi.com/owners/v2/owners
            params:
              email: "@profile.email"
        - id: pixiebrix/contrib-hubspot-company
          templateEngine: nunjucks
          config:
            name: name
            hubspot: "@hubspot"
            description: description
            website: "{% if companyPageUrl %}{{ companyPageUrl|safe }}{% elif callToAction.callToActionType == 'VIEW_WEBSITE' %}{{ callToAction.url|safe }}{% endif %}"
            hubspot_owner_id: "@owners.0?.ownerId"
