apiVersion: v1
kind: recipe
metadata:
  id: linkedin/pipedrive
  version: 0.0.1
  name: LinkedIn Pipedrive Activity
  description: Show a panel with Pipedrive activity on profile pages
extensionPoints:
  - id: "linkedin/person-panel"
    label: Pipedrive Activity
    config:
      heading: Pipedrive Activity for {{firstName}}
      body:
        id: pipedrive/person-activity
        config:
          personName: "{{&firstName}} {{&lastName}}"
          organizationName: currentCompanyName
