apiVersion: v1
kind: recipe
metadata:
  id: linkedin/company-news
  version: 0.0.1
  name: LinkedIn Company News
  description: Show NYTimes articles about companies
extensionPoints:
  - id: "linkedin/person-panel"
    label: NYTimes Articles
    config:
      heading: NYTimes Articles for {{currentCompanyName}}
      collapsible: True
      body:
        id: "nytimes/organization-articles"
        config:
          organizationName: currentCompanyName
  - id: "linkedin/organization-panel"
    label: NYTimes Articles
    config:
      heading: NYTimes Articles
      collapsible: True
      body:
        id: "nytimes/organization-articles"
        config:
          organizationName: name
