apiVersion: v1
kind: recipe
metadata:
  id: redfin/google-sheets
  version: 0.0.1
  name: Send Redfin Properties to Google Sheets
  description: Send properties you've found to Google Sheets
extensionPoints:
  - id: "redfin/property-button"
    label: Send Property to Google Sheets
    services:
      sheet: "google/sheet"
    config:
      caption: Sheets
      icon:
        id: googlesheets
        library: simple-icons
        size: 24
      action:
        - id: "@pixiebrix/google/sheets-append"
          config:
            spreadsheetId: "@sheet.spreadsheetId"
            tabName: "Redfin"
            rowValues:
              - header: Property Id
                value: propertyId
              - header: Listing Id
                value: listingId
              - header: Address
                value: addressSectionInfo.streetAddress.assembledAddress
              - header: City
                value: addressSectionInfo.city
              - header: State
                value: addressSectionInfo.state
              - header: Price
                value: addressSectionInfo.priceInfo.amount
              - header: Price Sq Ft
                value: addressSectionInfo.pricePerSqFt
              - header: "# Beds"
                value: addressSectionInfo.beds
              - header: "# Full Baths"
                value: addressSectionInfo.numFullBaths
              - header: "# Partial Baths"
                value: addressSectionInfo.numPartialBaths
              - header: Built
                value: addressSectionInfo.yearBuilt
              - header: Latitude
                value: addressSectionInfo.latLong.latitude
              - header: Longitude
                value: addressSectionInfo.latLong.longitude
              - header: Retrieved From
                value: document.url
