apiVersion: v1
kind: reader
metadata:
  id: linkedin/person-summary
  version: 0.2.0
  name: LinkedIn Profile Summary
  description: Read summary information from a LinkedIn profile
definition:
  reader:
    type: emberjs
    selector: ".pv-top-card"
    pathSpec:
      firstName: "memberName?.firstName"
      lastName: "memberName?.lastName"
      followersCount: "followersCount"
      vanityName: "vanityName"
      vanityUrl: "model?.vanityUrl"
      headline: "headline"
      isInfluencer: "isInfluencer"
      currentCompanyName: "currentCompanyName"
      geoLocationName: "geoLocationName"
      locationName: "locationName"
      schoolName: "schoolName"
  isAvailable:
    matchPatterns: "https://*.linkedin.com/*"
    selectors: "#profile-content"
outputSchema:
  type: object
  properties:
    firstName:
      type: string
    lastName:
      type: string
    followersCount:
      type: number
    vanityName:
      type: string
    vanityUrl:
      type: string
      format: uri
    headline:
      type: string
    isInfluencer:
      type: boolean
    currentCompanyName:
      type: string
    geoLocationName:
      type: string
    locationName:
      type: string
    schoolName:
      type: string
