apiVersion: v1
kind: service
metadata:
  id: serpapi/api
  version: 0.0.1
  name: SerpAPI
  description: Access Google, Ebay, Walmart and services via API
  url: https://serpapi.com/
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    apiKey:
      $ref: "https://app.pixiebrix.com/schemas/key#"
      description: Your SerpAPI key
  required:
    - apiKey
authentication:
  params:
    api_key: "{{apiKey}}"
