apiVersion: v1
kind: component
metadata:
  id: "ebay/search"
  version: 1.0.0
  name: eBay search in new tab
  description: Runs a eBay search in a new tab
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    query:
      type: string
      description: The search query
  required:
    - query
pipeline:
  - id: "@pixiebrix/browser/open-tab"
    config:
      url: https://www.ebay.com/sch/
      params:
        _nkw: query
