name: Release Build

on:
  push:
    branches:
      - 'releases/**'

jobs:
  build-chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build:chrome
        env:
          NODE_ENV: production
          ENVIRONMENT: production
          ROLLBAR_PUBLIC_PATH: chrome-extension://production/
          CHROME_EXTENSION_ID: mpjjildhmpddojocokjkgmlkkkfjnepo
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          SERVICE_URL: https://app.pixiebrix.com
          EXTERNALLY_CONNECTABLE: https://app.pixiebrix.com
          ROLLBAR_BROWSER_ACCESS_TOKEN: ${{ secrets.ROLLBAR_BROWSER_ACCESS_TOKEN }}
          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: chrome-production
          path: browsers/chrome/bundles
          retention-days: 5

  build-firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build:firefox
        env:
          NODE_ENV: production
          ENVIRONMENT: production
          ROLLBAR_PUBLIC_PATH: moz-extension://production/
          SERVICE_URL: https://app.pixiebrix.com
          ROLLBAR_BROWSER_ACCESS_TOKEN: ${{ secrets.ROLLBAR_BROWSER_ACCESS_TOKEN }}
          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: firefox-production
          path: browsers/firefox/bundles
          retention-days: 5
