name: CI

on: push

env:
  # Creates and uploads sourcemaps to Rollbar, and save the built extension as an artifact
  PUBLIC_RELEASE: ${{ github.ref == 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # 16.15.1 was having problems with peer dependency conflicts
          # https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
          node-version: "16.15.0"
          cache: npm
      - run: npm ci
      - run: npm run test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true

  build-stage:
    runs-on: ubuntu-latest
    env:
      SOURCE_MAP_URL_BASE: https://pixiebrix-extension-source-maps.s3.amazonaws.com
      SOURCE_MAP_PATH: sourcemaps/${{ github.job }}/${{ github.sha }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # 16.15.1 was having problems with peer dependency conflicts
          # https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
          node-version: "16.15.0"
          cache: npm
      - run: npm ci
      - run: npm run build:webpack
        env:
          ENVIRONMENT: staging
          EXTERNALLY_CONNECTABLE: ${{ secrets.STAGING_SERVICE_URL }}*,http://127.0.0.1/*
          SERVICE_URL: ${{ secrets.STAGING_SERVICE_URL }}
          ROLLBAR_BROWSER_ACCESS_TOKEN: ${{ secrets.ROLLBAR_BROWSER_ACCESS_TOKEN }}
          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}
          CHROME_EXTENSION_ID: kkomancachnjkdalpcokenmjlimmbaog
          CHROME_MANIFEST_KEY: ${{ secrets.CHROME_MANIFEST_STAGING_PUBLIC_KEY }}
          GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
          GOOGLE_API_KEY: ${{ secrets.STAGE_GOOGLE_API_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.STAGE_GOOGLE_OAUTH_CLIENT_ID }}
      - name: Save extension
        uses: ./.github/actions/upload-zipped-artifact
        if: ${{ fromJSON(env.PUBLIC_RELEASE)}}
        with:
          name: build-staging
          directory: dist
          exclusions: "*.map"
          retention-days: 5
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        name: Save report.html
        with:
          name: staging-build-size
          path: report.html
          retention-days: 5
          if-no-files-found: error

  # Slow, and we don't use currently
  #      - run: bash scripts/upload-sourcemaps.sh
  #        if: ${{ fromJSON(env.PUBLIC_RELEASE)}}
  #        env:
  #          AWS_ACCESS_KEY_ID: ${{ secrets.SOURCEMAP_USER_ID }}
  #          AWS_SECRET_ACCESS_KEY: ${{ secrets.SOURCEMAP_USER_KEY }}
  #          AWS_DEFAULT_REGION: "us-east-2"
  #          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}

  generate-headers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # 16.15.1 was having problems with peer dependency conflicts
          # https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
          node-version: "16.15.0"
          cache: npm
      - run: npm ci
      - run: npm run build:scripts
      - run: npm run generate:headers
      - uses: actions/upload-artifact@v2
        name: Save headers.json
        with:
          name: brick-headers
          path: headers.json
          retention-days: 5
          if-no-files-found: error

  types:
    # Surface type errors in GitHub’s UI faster and outside webpack
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # 16.15.1 was having problems with peer dependency conflicts
          # https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
          node-version: "16.15.0"
          cache: npm
      - run: npm ci
      - run: npm run build:typescript

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # 16.15.1 was having problems with peer dependency conflicts
          # https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
          node-version: "16.15.0"
          cache: npm
      - run: npm ci
      - run: npm run lint -- --quiet

  circular-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # 16.15.1 was having problems with peer dependency conflicts
          # https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
          node-version: "16.15.0"
          cache: npm
      # Fixed version to avoid random breaks. Not in package.json due to #1084
      - run: npm install --global madge@5.0.1
      - run: npm run madge:circular
        name: Detect circular dependencies

  # https://pre-commit.com/#usage-in-continuous-integration
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
