name: Pre-release Browsers

on:
  schedule:
    # Run nightly at 1:00 AM EST (5:00 UTC)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  end-to-end-tests:
    name: end-to-end-tests
    uses: ./.github/workflows/end-to-end-tests.yml
    secrets: inherit
    with:
      # Include stable browsers for comparison
      projects: '["chrome-beta", "msedge-beta", "chromium", "chrome", "msedge"]'

  slack-notification:
    needs: end-to-end-tests
    runs-on: ubuntu-latest
    if: ${{ job.status == 'failure' }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: playwright-playground
          SLACK_MESSAGE: "Nightly pre-release browser tests failed"
          SLACK_COLOR: ${{ job.status }}
