name: Pre-release Browsers

on:
  schedule:
    # Run nightly at 1:00 AM EST (5:00 UTC)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  end-to-end-tests:
    name: end-to-end-tests
    uses: ./.github/workflows/end-to-end-tests.yml
    secrets: inherit
    with:
      # Include stable browsers for comparison
      projects: '["chrome-beta", "msedge-beta", "chromium", "chrome", "msedge"]'
