name: end-to-end-tests

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: "Branch, tag, or commit on which to run the tests"
        required: false
        type: string

jobs:
  run-tests:
    name: run-tests
    strategy:
      fail-fast: false
      matrix:
        project: [chrome, edge]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SHADOW_DOM: open
      SERVICE_URL: https://app.pixiebrix.com
      MV: 3
      RELEASE_CHANNEL: stable
      CHROME_MANIFEST_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhYpgz6Nt3vv5n3d8jyrsWXjkvAxh7bz8WJW05RFrtJx9t0BiVVclO+WpAmhKanB2BiTDw4+Dnlf2lQfTo62LIBnkfTiGzukKqTu3plF0D/Tl/yG1st1xKaQ6dekeThcsgxrFD8+kIUwF4Vq0wPpQ5upl+vf6kX4t9eDev8Eg86mHzUEG/QoS/bu5evN3I1Z0HsiF84VWlrV0b/1GSqpn+dMrFFdcwo2Sn0Ec65nSNfzauDUm5n0NToQ8iYdHkuottREXKJ7/Uy4tO0eMmfokVixbm0i2m9aHEOior5CmNG9X/yGtR2CiM1N4DSEY5mTFu5hPOrALspJ+t7+Is7YnFwIDAQAB
      DATADOG_APPLICATION_ID: ${{ secrets.DATADOG_APPLICATION_ID }}
      DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
      REQUIRE_OPTIONAL_PERMISSIONS_IN_MANIFEST: 1
      E2E_TEST_USER_EMAIL_UNAFFILIATED: ${{ secrets.E2E_TEST_USER_EMAIL_UNAFFILIATED }}
      E2E_TEST_USER_PASSWORD_UNAFFILIATED: ${{ secrets.E2E_TEST_USER_PASSWORD_UNAFFILIATED }}
      E2E_GOOGLE_TEST_USER_EMAIL: ${{ secrets.E2E_GOOGLE_TEST_USER_EMAIL }}
      E2E_GOOGLE_TEST_USER_PASSWORD: ${{ secrets.E2E_GOOGLE_TEST_USER_PASSWORD }}
      E2E_GOOGLE_TEST_USER_OTP_KEY: ${{ secrets.E2E_GOOGLE_TEST_USER_OTP_KEY }}
      DEV_EVENT_TELEMETRY: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.checkout-ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        uses: Wandalen/wretry.action@v3.5.0
        with:
          command: npx playwright install chrome msedge
          with: |
            fail_ci_if_error: true
            verbose: true
            token: ${{ secrets.CODECOV_TOKEN }}
          # Installing msedge is flaky due to failed checksums from the Microsoft CDN. Unclear why this happens.
          # Retry every 15 seconds, for up to 10 minutes
          attempt_delay: 15000
          attempt_limit: 40
      - name: Build the extension
        run: npm run build:webpack
      - name: Run end to end tests
        # Xvfb is required to run the tests in headed mode. Headed mode is required to run tests for browser extensions
        # in Playwright, see https://playwright.dev/docs/ci#running-headed
        run: xvfb-run npm run test:e2e -- --project=${{ matrix.project }}*
      - name: Password protect Playwright reports
        if: always()
        shell: bash
        env:
          ARTIFACT_ZIP_PASSWORD: ${{ secrets.ARTIFACT_ZIP_PASSWORD }}
        run: 7z a ./end-to-end-tests/blob-report-${{ matrix.project }}.7z ./end-to-end-tests/.blob-report/* -p"$ARTIFACT_ZIP_PASSWORD"
      - name: Upload zipped Playwright Report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: end-to-end-tests-report-${{ matrix.project }}
          path: end-to-end-tests/blob-report-${{ matrix.project }}.7z
          retention-days: 5
          compression-level: 0 # already compressed with 7z
