name: Inclusiveness Analyzer
on:
  push:
  workflow_dispatch:

jobs:
  # Analyzer for checking for inclusive terminology in code. For more information, see
  # https://github.com/microsoft/InclusivenessAnalyzer
  Inclusiveness-Analyser-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inclusiveness Analyzer
        uses: microsoft/InclusivenessAnalyzer@v1.0.1
