name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - run: npm ci
      - run: npm test

  stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          ENVIRONMENT: staging
          EXTERNALLY_CONNECTABLE: ${{ secrets.STAGING_SERVICE_URL }}*,http://127.0.0.1/*
          SERVICE_URL: ${{ secrets.STAGING_SERVICE_URL }}
          ROLLBAR_BROWSER_ACCESS_TOKEN: ${{ secrets.ROLLBAR_BROWSER_ACCESS_TOKEN }}
          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}
          SUPPORT_WIDGET_ID: ${{ secrets.SUPPORT_WIDGET_ID }}
          CHROME_EXTENSION_ID: kkomancachnjkdalpcokenmjlimmbaog
          CHROME_MANIFEST_KEY: ${{ secrets.CHROME_MANIFEST_STAGING_PUBLIC_KEY }}
          GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
          GOOGLE_API_KEY: ${{ secrets.STAGE_GOOGLE_API_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.STAGE_GOOGLE_OAUTH_CLIENT_ID }}
      - name: BrowserStack Env Setup # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          # https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
          build-name: ${{ github.workflow }} - ${{ github.run_id }}
          project-name: pixiebrix-extension
      - name: Running test on BrowserStack
        # Invokes the actual test script that would run on BrowserStack browsers
        run: node selenium/sample-build.js
      - uses: actions/upload-artifact@v2
        with:
          name: build-staging
          path: dist
          retention-days: 5
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: staging-build-size
          path: report.html
          retention-days: 5
          if-no-files-found: error

  test-on-gha:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          ENVIRONMENT: staging
          EXTERNALLY_CONNECTABLE: ${{ secrets.STAGING_SERVICE_URL }}*,http://127.0.0.1/*
          SERVICE_URL: ${{ secrets.STAGING_SERVICE_URL }}
          ROLLBAR_BROWSER_ACCESS_TOKEN: ${{ secrets.ROLLBAR_BROWSER_ACCESS_TOKEN }}
          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}
          SUPPORT_WIDGET_ID: ${{ secrets.SUPPORT_WIDGET_ID }}
          CHROME_EXTENSION_ID: kkomancachnjkdalpcokenmjlimmbaog
          CHROME_MANIFEST_KEY: ${{ secrets.CHROME_MANIFEST_STAGING_PUBLIC_KEY }}
          GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
          GOOGLE_API_KEY: ${{ secrets.STAGE_GOOGLE_API_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.STAGE_GOOGLE_OAUTH_CLIENT_ID }}
      - name: Running test on GitHub Actions
        run: node selenium/sample-build.js

  generate-headers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - run: npm ci
      - run: npm run build:scripts
      - run: node scripts/bin/headers.js
      - uses: actions/upload-artifact@v2
        with:
          name: brick-headers
          path: headers.json
          retention-days: 5
          if-no-files-found: error

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - run: npm ci
        # Run eslint without GitHub Actions annotations
        # https://stackoverflow.com/a/65964721/288906
      - name: npm run lint
        run: |
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"
          npm run lint
