name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - run: npm test
        env:
          CI: true

  stage-chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - run: npm run build:chrome
        env:
          NODE_ENV: production
          ENVIRONMENT: staging
          ROLLBAR_PUBLIC_PATH: chrome-extension://staging/
          CHROME_EXTENSION_ID: kkomancachnjkdalpcokenmjlimmbaog
          CHROME_MANIFEST_KEY: ${{ secrets.CHROME_MANIFEST_STAGING_PUBLIC_KEY }}
          GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
          GOOGLE_API_KEY: ${{ secrets.STAGE_GOOGLE_API_KEY }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.STAGE_GOOGLE_OAUTH_CLIENT_ID }}
          EXTERNALLY_CONNECTABLE: ${{ secrets.STAGING_SERVICE_URL }}*,http://127.0.0.1/*
          SERVICE_URL: ${{ secrets.STAGING_SERVICE_URL }}
          ROLLBAR_BROWSER_ACCESS_TOKEN: ${{ secrets.ROLLBAR_BROWSER_ACCESS_TOKEN }}
          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}
          ENABLE_DEVTOOLS: true
          SUPPORT_WIDGET_ID: ${{ secrets.SUPPORT_WIDGET_ID }}
      - uses: actions/upload-artifact@v2
        with:
          name: chrome-staging
          path: browsers/chrome/bundles
          retention-days: 5
      - uses: actions/upload-artifact@v2
        with:
          name: chrome-bundle-size
          path: report.html
          retention-days: 5

  stage-firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - run: npm run build:firefox
        env:
          NODE_ENV: production
          ENVIRONMENT: staging
          ROLLBAR_PUBLIC_PATH: moz-extension://staging/
          SERVICE_URL: ${{ secrets.STAGING_SERVICE_URL }}
          ROLLBAR_BROWSER_ACCESS_TOKEN: ${{ secrets.ROLLBAR_BROWSER_ACCESS_TOKEN }}
          ROLLBAR_POST_SERVER_ITEM_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_TOKEN }}
          SUPPORT_WIDGET_ID: ${{ secrets.SUPPORT_WIDGET_ID }}
      - uses: actions/upload-artifact@v2
        with:
          name: firefox-staging
          path: browsers/firefox/bundles
          retention-days: 5
      - uses: actions/upload-artifact@v2
        with:
          name: firefox-bundle-size
          path: report.html
          retention-days: 5

  generate-headers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - run: npm run build:scripts
      - run: node scripts/bin/headers.js
      - uses: actions/upload-artifact@v2
        with:
          name: brick-headers
          path: headers.json
          retention-days: 5
