name: Storybook

on: [push]

jobs:
  storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          # 16.15.1 was having problems with peer dependency conflicts
          # https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
          node-version: "16.15.0"
          cache: npm
      - run: npm ci
      - run: npm run build-storybook
      - name: Upload Storybook
        # Upload zipped artifact because otherwise upload is slow due to a lot of small files (for the icons)
        uses: ./.github/actions/upload-zipped-artifact
        with:
          name: storybook
          directory: storybook-static
          if-no-files-found: error
          retention-days: 3
