name: Storybook

on: [push]

jobs:
  storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm
      - run: npm ci
      - run: npm run build-storybook
# Upload is very slow since there is a lot of small files (for the icons). Leave off for now so it doesn't slow down CI
#      - uses: actions/upload-artifact@v2
#        with:
#          name: storybook
#          path: storybook-static
#          retention-days: 3
#          if-no-files-found: error
